### ISSUE TITLE
TabScope shows it's miniatures only on the Primary display

### ISSUE THREAD

**Issue by Drugoy** [gomita/tabscope#33]
So if you have 2 displays and Fx window is not on the primary one, then tabscope miniatures appear on another display.

**Comment by spok7** [comment]
It's been over four years, and this issue has not yet been resolved. It would be very convenient if Tab Scope would be able able to show on secondary screens when the Firefox window is also on a secondary screen. Meanwhile, the pop-up displays on the right-most side of the primary screen (presumably because my secondary screen is to the right of my primary one). Surprisingly, it still shows the popup at the correct height, so that's a plus.

This has not been the first case in which I have seen plugins UI displaying content only on primary screens; Classic Theme Restorer (v. 1.4.0) and InstantFox (v. 3.0.0.2-signed) both have a similar bug. It is possible to open their settings options through their toolbar icons, but the settings themselves appear on the primary screen. Strangely enough, all of my other plugins which do not have toolbar settings icons, display their settings menus on the same screen as Firefox. I hope this helps.

**Comment by dev-coder** [comment]
I have the same trouble at times (not always) and I use dual monitors running Windows side by side though. Once it opens on the wrong window even closing and restarting firefox doesn't seem to fix it. A log off or reboot does though. Not sure why it sometimes happens and not other times.
In my specific case I usually run firefox on my 2nd monitor (on the right). But these wrong placed popups show up on the left.
And this occurs whether I have the pop-up location set to "below tab" or "auto".
